POSTGRES_USER = "joshhager"
POSTGRES_PASS = ""
POSTGRES_HOST = "localhost"
POSTGRES_PORT = "5432"
DB_NAME = "employee_db"
CLEAN_DATA_TABLE_NAME = "employee_data"
CLEAN_DATA_FILEPATH = "employee_data_clean.csv"